version: '3.9'

services:
  about_service:
    container_name: user-services
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5003:5003
    volumes:
      - .:/product-service
