version: '3.9'

services:
  about_service:
    restart: always
    container_name: about-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5001:5001
    volumes:
      - .:/about_service
